import { AdminPanelNavigationSection } from './models/admin-panel-navigation.model';

export const ADMIN_PANEL_NAVIGATION_SECTIONS: readonly AdminPanelNavigationSection[] = [
  {
    key: 'workspace',
    labelKey: 'adminPanel.section.workspace',
    pages: [
      {
        key: 'team',
        icon: 'people',
        labelKey: 'adminPanel.section.team',
        route: '/admin-panel/workspace/team',
        badgeTextKey: null,
        adminOnly: true,
        ownerOnly: false,
      },
    ],
  },
  {
    key: 'articles',
    labelKey: 'adminPanel.section.articles',
    pages: [
      {
        key: 'articles',
        icon: 'document',
        labelKey: 'shell.nav.articles',
        route: '/admin-panel/articles',
        badgeTextKey: null,
        adminOnly: false,
        ownerOnly: false,
      },
      {
        key: 'article-folders',
        icon: 'folder',
        labelKey: 'adminPanel.section.articleFolders',
        route: '/admin-panel/article-folders',
        badgeTextKey: null,
        adminOnly: false,
        ownerOnly: false,
      },
      {
        key: 'article-tags',
        icon: 'document',
        labelKey: 'adminPanel.section.articleTags',
        route: '/admin-panel/article-tags',
        badgeTextKey: null,
        adminOnly: false,
        ownerOnly: false,
      },
      {
        key: 'article-statistics',
        icon: 'dashboard',
        labelKey: 'articles.stats.button',
        route: '/admin-panel/article-statistics',
        badgeTextKey: null,
        adminOnly: false,
        ownerOnly: false,
      },
    ],
  },
  {
    key: 'matrix',
    labelKey: 'shell.nav.matrix',
    pages: [
      {
        key: 'matrix-statistics',
        icon: 'dashboard',
        labelKey: 'articles.stats.button',
        route: '/admin-panel/matrix-statistics',
        badgeTextKey: null,
        adminOnly: false,
        ownerOnly: false,
      },
      {
        key: 'matrix-questions',
        icon: 'document',
        labelKey: 'adminPanel.section.matrixQuestions',
        route: '/admin-panel/matrix-questions',
        badgeTextKey: null,
        adminOnly: false,
        ownerOnly: false,
      },
      {
        key: 'matrix-structure',
        icon: 'folder',
        labelKey: 'adminPanel.section.matrixStructure',
        route: '/admin-panel/matrix-structure',
        badgeTextKey: null,
        adminOnly: false,
        ownerOnly: false,
      },
      {
        key: 'matrix-question-queue',
        icon: 'people',
        labelKey: 'adminPanel.section.matrixQuestionQueue',
        route: '/admin-panel/matrix-question-queue',
        badgeTextKey: null,
        adminOnly: false,
        ownerOnly: false,
      },
    ],
  },
];
