import { MarkdownEditorLabels } from '@alittlemore.dev/design-system/markdown-editor';
import { I18nService } from '../i18n/i18n.service';

export function markdownEditorLabels(i18n: I18nService): MarkdownEditorLabels {
  return {
    mode: {
      aria: i18n.translate('markdownEditor.mode.aria'),
      edit: i18n.translate('markdownEditor.mode.edit'),
      source: i18n.translate('markdownEditor.mode.source'),
      preview: i18n.translate('markdownEditor.mode.preview'),
    },
    fullscreen: {
      enter: i18n.translate('markdownEditor.fullscreen.enter'),
      exit: i18n.translate('markdownEditor.fullscreen.exit'),
    },
    toolbar: {
      aria: i18n.translate('markdownEditor.toolbar.aria'),
    },
    commands: {
      togglePreview: i18n.translate('markdownEditor.command.togglePreview'),
      toggleSource: i18n.translate('markdownEditor.command.toggleSource'),
      heading1: i18n.translate('markdownEditor.command.heading1'),
      heading2: i18n.translate('markdownEditor.command.heading2'),
      heading3: i18n.translate('markdownEditor.command.heading3'),
      heading4: i18n.translate('markdownEditor.command.heading4'),
      heading5: i18n.translate('markdownEditor.command.heading5'),
      heading6: i18n.translate('markdownEditor.command.heading6'),
      bold: i18n.translate('markdownEditor.command.bold'),
      italic: i18n.translate('markdownEditor.command.italic'),
      strikethrough: i18n.translate('markdownEditor.command.strikethrough'),
      quote: i18n.translate('markdownEditor.command.quote'),
      unorderedList: i18n.translate('markdownEditor.command.unorderedList'),
      orderedList: i18n.translate('markdownEditor.command.orderedList'),
      taskList: i18n.translate('markdownEditor.command.taskList'),
      horizontalRule: i18n.translate('markdownEditor.command.horizontalRule'),
      link: i18n.translate('markdownEditor.command.link'),
      image: i18n.translate('markdownEditor.command.image'),
      inlineCode: i18n.translate('markdownEditor.command.inlineCode'),
      codeBlock: i18n.translate('markdownEditor.command.codeBlock'),
      table: i18n.translate('markdownEditor.command.table'),
      search: i18n.translate('markdownEditor.command.search'),
    },
    shortcutGroups: {
      view: i18n.translate('markdownEditor.shortcuts.group.view'),
      headings: i18n.translate('markdownEditor.shortcuts.group.headings'),
      inline: i18n.translate('markdownEditor.shortcuts.group.inline'),
      blocks: i18n.translate('markdownEditor.shortcuts.group.blocks'),
      media: i18n.translate('markdownEditor.shortcuts.group.media'),
    },
    shortcuts: {
      summary: i18n.translate('markdownEditor.shortcuts.summary'),
      modifierHintMac: i18n.translate('markdownEditor.shortcuts.modifierHintMac'),
      modifierHintOther: i18n.translate('markdownEditor.shortcuts.modifierHintOther'),
      tabEscape: i18n.translate('markdownEditor.shortcuts.tabEscape'),
    },
    search: {
      find: i18n.translate('markdownEditor.search.find'),
      replace: i18n.translate('markdownEditor.search.replace'),
      next: i18n.translate('markdownEditor.search.next'),
      previous: i18n.translate('markdownEditor.search.previous'),
      all: i18n.translate('markdownEditor.search.all'),
      matchCase: i18n.translate('markdownEditor.search.matchCase'),
      byWord: i18n.translate('markdownEditor.search.byWord'),
      regexp: i18n.translate('markdownEditor.search.regexp'),
      replaceAll: i18n.translate('markdownEditor.search.replaceAll'),
      close: i18n.translate('markdownEditor.search.close'),
      goToLine: i18n.translate('markdownEditor.search.goToLine'),
      go: i18n.translate('markdownEditor.search.go'),
      currentMatch: i18n.translate('markdownEditor.search.currentMatch'),
      onLine: i18n.translate('markdownEditor.search.onLine'),
      replacedMatches: i18n.translate('markdownEditor.search.replacedMatches'),
      replacedMatchOnLine: i18n.translate('markdownEditor.search.replacedMatchOnLine'),
    },
    preview: {
      empty: i18n.translate('markdownEditor.preview.empty'),
      imageFailed: i18n.translate('markdownEditor.preview.imageFailed'),
    },
    wikiLinks: {
      registryUnavailable: i18n.translate('markdownEditor.wikiLinks.registryUnavailable'),
    },
    table: {
      table: i18n.translate('markdownEditor.table.table'),
      row: i18n.translate('markdownEditor.table.row'),
      column: i18n.translate('markdownEditor.table.column'),
      range: i18n.translate('markdownEditor.table.range'),
      menu: i18n.translate('markdownEditor.table.menu'),
      addRow: i18n.translate('markdownEditor.table.addRow'),
      addColumn: i18n.translate('markdownEditor.table.addColumn'),
      moveRow: i18n.translate('markdownEditor.table.moveRow'),
      moveColumn: i18n.translate('markdownEditor.table.moveColumn'),
      insertBefore: i18n.translate('markdownEditor.table.insertBefore'),
      insertAfter: i18n.translate('markdownEditor.table.insertAfter'),
      duplicate: i18n.translate('markdownEditor.table.duplicate'),
      clear: i18n.translate('markdownEditor.table.clear'),
      copy: i18n.translate('markdownEditor.table.copy'),
      cut: i18n.translate('markdownEditor.table.cut'),
      delete: i18n.translate('markdownEditor.table.delete'),
      moveBefore: i18n.translate('markdownEditor.table.moveBefore'),
      moveAfter: i18n.translate('markdownEditor.table.moveAfter'),
      sortAscending: i18n.translate('markdownEditor.table.sortAscending'),
      sortDescending: i18n.translate('markdownEditor.table.sortDescending'),
      alignLeft: i18n.translate('markdownEditor.table.alignLeft'),
      alignCenter: i18n.translate('markdownEditor.table.alignCenter'),
      alignRight: i18n.translate('markdownEditor.table.alignRight'),
      format: i18n.translate('markdownEditor.table.format'),
      deleteTable: i18n.translate('markdownEditor.table.deleteTable'),
      clipboardFailed: i18n.translate('markdownEditor.table.clipboardFailed'),
    },
    completions: i18n.translate('markdownEditor.completions'),
    upload: {
      uploading: i18n.translate('markdownEditor.upload.uploading'),
      retry: i18n.translate('markdownEditor.upload.retry'),
      dismiss: i18n.translate('markdownEditor.upload.dismiss'),
      failed: (fileName) => i18n.translate('markdownEditor.upload.failed', { fileName }),
      unsupported: (fileName) => i18n.translate('markdownEditor.upload.unsupported', { fileName }),
    },
  };
}
